# Generated by Django 3.2.5 on 2021-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210710_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='/images/heart.png', upload_to='images'),
        ),
    ]
